spring:
  liquibase:
    enabled: true
    change-log: classpath:db.changelog/db.changelog-master.xml

  datasource:
    url: jdbc:postgresql://postgres:5432/bricklydb
    username: bricklyuser
    password: bricklypass
    driver-class-name: org.postgresql.Driver

  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000
          multiplier: 2.0
          max-interval: 10000

  servlet:
    multipart:
      enabled: true
      max-file-size: 15MB
      max-request-size: 70MB
      file-size-threshold: 2KB
      resolve-lazily: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationSorter: method

app:
  upload:
    base-dir: /app/uploads

gpt:
  api:
    key: ${GPT_API_KEY}
    url: http://104.128.139.152:8888/v1/chat/completions
    timeout: 10000
    model: gpt-5-nano
    temperature: 0.3

yookassa:
  shop-id: ${YOOKASSA_SHOP_ID}
  secret-key: ${YOOKASSA_SECRET_KEY}
  url: https://api.yookassa.ru/v3