spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_UPPER=false;CASE_INSENSITIVE_IDENTIFIERS=TRUE
  #    url: jdbc:postgresql://postgres@localhost:5432/postgres

  h2:
    console:
      enabled: true

  liquibase:
    enabled: true
    change-log: classpath:db.changelog/db.changelog-master.xml

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true

  spring-doc:
    swagger-ui:
      path: /swagger-ui.html
      operationsSorter: method